import { base } from "$app/paths";

export const base_url = `https://palopenmaps.org`;
export const locs_url = `${base}/data/places.json`;
export const redirect_url = `${base}/data/redirects.csv`;
export const layers_url = `${base_url}/api/layers/`;
export const sheets_url = `${base_url}/api/sheets/`;

export const maxBounds = [[33.5, 29.0], [36.4, 33.9]];

export const statuses = {
	Remaining: {
		name: "Remaining",
		color: "#7ac943",
		selected: true,
	},
	Depopulated: {
		name: "Depopulated",
		color: "#fcee21",
		selected: true,
	},
	Appropriated: {
		name: "Depopulated & appropriated",
		color: "#f7931e",
		selected: true,
	},
	"Built over": {
		name: "Depopulated & built over",
		color: "#ff0000",
		selected: true,
	},
	Abandoned: {
		name: "Abandoned",
		color: "#0099ff",
		selected: false,
	},
	"Newly built": {
		name: "New locality",
		color: "#777777",
		selected: false,
	}
};

export const pages = [
	{
		key: "about",
		label: "About",
		icon: "info",
		id: { en: 3, ar: 7 }
	},
	// {
	// 	key: "vision",
	// 	label: "Project vision",
	// 	icon: "stars",
	// 	id: {en: 5, ar: 8}
	// },
	{
		key: "get-involved",
		label: "Get involved",
		icon: "hand",
		id: { en: 6, ar: 9 }
	}
];

export const layers_added = [
	{
		"id": 16,
		"name": "Aerial imagery, 1944-48",
		"description": "A layer compiled from black and white aerial photographs captured by the British military in the 1940s. It is color-corrected and merged together into a single raster tileset.",
		"boundaries": null,
		"scale": 1,
		"start_year": "1944-01-01",
		"end_year": "1948-05-15",
		"url": "https://cdn.jsdelivr.net/gh/bothness/pom-tiles/aerial1940s/{z}/{x}/{y}.png",
		"attribution": "Royal Air Force, 1940s",
		"is_active": false,
		"is_default": false,
		"is_overlay": false,
		"order": -1,
		"author": 10,
		"sources": [36],
		"further_readings": []
	}
];

export const texts = {
	"ar": {
		"العربية": "English",
		"ع": "en",
		"Explore, search and download historical maps and spatial data on Palestine": "استكشِف/ي وتصفّح/ي وحمّل/ي خرائط وبيانات مَكانيّة عَن فِلسطين",
		"Welcome to<br>Palestine Open Maps": "أهلًا بكم/ن في منصّة<br>خرائط فلسطين المفتوحة",
		"Explore maps": "استكشف/ي الخرائط",
		"Read More": "اقرأ/ي المزيد",
		"Find a Place": "ابحث/ي عن موقِع",
		"Explore historical maps from the 1870s onwards": "استكشف/ي خرائط تاريخيّة منذ  عام 1870 حتى يومنا هذا",
		"View data on over 2,000 places, past and present": "تصفّح/ي بيانات عن أكثر من 2000 موقع بين الماضي والحاضر",
		"Download hundreds of historical map sheets": "حمّل/يل مئات الخرائط التّاريخية",
		"View past and present maps side-by-side": "قارن/ي خرائط من الماضي والحاضر جنبًا إلى جنب",
		"View the topography of Palestine in 3D": "استكشف/ي تضاريس فلسطين ثلاثية الأبعاد",
		"Overlay historical and present day maps": "استكشف/ي التغييرات بين الماضي والحاضر من خلال تركيب الخرائط من حقبات مختلفة",
		"Initiated and supported by Visualising Palestine": "بمُبادرة ودَعم من Visualising Palestine",
		"Home": "الصّفحة الرئيسيّة",
		"Explore maps": "استكشف/ي الخرائط",
		"About": "عن خرائط فلسطين المفتوحة",
		"Get involved": "انضم/ي لنا",
		"Blog": "المُدوّنة",
		"Contact": "تواصل/ي معنا",
		"Find a place": "ابحث/ي عن موقع",
		"Base maps": "خرائط أساسيّة",
		"Aerial imagery, 1940s": "تصوير جوّي، عَقد 1940",
		"Satellite imagery, 2022": "تصوير أقمار اصطناعيّة، 2022",
		"Western Palestine, 1:63,000, 1870s": "فلسطين الغربيّة، 1:63000، عَقد 1870",
		"Palestine, 1:20,000, 1940s": "فلسطين: 1:20000، عقدَي 1940/",
		"Palestine, 1:100,000, 1940s/50s": "فلسطين: 1:100000، عقدَي 1940/50",
		"Palestine, 1:250,000, 1946": "فلسطين: 1:250000، 1946",
		"Israel, 1:250,000, 1951": "إسرائيل: 1:250000، 1951",
		"Combined Maps, 1930s/40s": "خرائط مركّبة، عقدَي 1930/40",  
		"Overlays": "الطبقات",
		"Show overlays": "عَرض الطَّبَقات",
		"Vector overlay, 1940s": "طَبقات مُتّجهة، عَقد 1940",
		"Vector overlay, 2020s": "طَبقات مُتّجهة، عقد 2020",
		"Buildings": "منشآت عمرانية",
		"Roads/rail": "طُرق/سِكَك",
		"Place names": "أسماء الأماكن",
		"Places": "أماكن",
		"Show places": "عَرض الأماكن",
		"Remaining": "صامدة",
		"Depopulated": "مهجّرة",
		"Depopulated & appropriated": "مهجّرة ومُصادرة",
		"Depopulated & built over": "مهجّرة وبُني فَوقها",
		"Abandoned": "مهجورة",
		"New locality": "مَنطقة جَديدة",
		"Download maps": "تحميل الخرائط",
		"Click anywhere on the map to see sheets available to download covering that location.": "انقر/ي على أي نُقطة في الخريطة لعَرض الشّرائح المُتاحة للتّحميل حَول الموقِع",
		"Toggle split-screen": "تَفعيل الشّاشة المُزدوجة",
		"Toggle 3D (experimental)": "تفعيل الرؤية ثلاثية الأبعاد",
		"Home": "الصّفحة الرئيسيّة",
		"Explore maps": "استكشف/ي الخرائط",
		"About": "عن خرائط فلسطين المفتوحة",
		"Get involved": "انضم/ي لنا",
		"Blog": "المدوّنة",
		"Contact": "تواصل/ي معنا",
		"Get involved": "انضم/ي لنا",
		"Initiated and supported by Visualising Palestine": "بمُبادرة ودَعم من Visualising Palestine",
		"Palestine Open Maps": "خَرائط فلسطين المَفتوحة",
		"Palestine Open Maps community": "مُجتمع خَرائط فلسطين المَفتوحة",
		"Base maps": "الخرائط الأساسيّة",
		"Overlays": "طَبقات",
		"Places": "أماكن",
		"Get updates": "احصل/ي على  أخبار المشروع",
		"Download maps": "تحميل الخرائط",
		"Home": "الصّفحة الرئيسيّة",
		"About": "عن خرائط فلسطين المفتوحة",
		"Get involved": "انضم/ي لنا",
		"Blog": "المدوّنة",
		"Contact": "تَواصل/ي معنا",
		"Project vision": "رؤية المشروع",
		"Support us": "إدعم/ينا",
		"Explore maps": "استكشف/ي الخرائط",
		"Toggle split-screen": "تَفعيل الشّاشة المُزدوجة",
		"Toggle 3D (experimental)": "تفعيل الرؤية ثلاثية الأبعاد",
		"Toggle places": "عَرض الأماكن",
		"Toggle overlays": "عَرض الطّبقات",
		"Show layer information": "رؤية معلومات عن الطّبقة",
		"Find a place": "ابحث/ي عن موقع",
		"Aerial imagery, 1940s": "تصوير جوّي، عَقد 1940",
		"Satellite imagery, 2022": "تصوير أقمار اصطناعيّة، 2022",
		"Western Palestine, 1:63,000, 1870s": "فلسطين الغربيّة، 1:63000، عَقد 1870",
		"Palestine, 1:20,000, 1940s": "فلسطين: 1:20000، عَقد 1940",
		"Palestine, 1:100,000, 1940s/50s": "فلسطين: 1:100000، عقدَي 1940/50",
		"Palestine, 1:250,000, 1946": "فلسطين: 1:250000، 1946",
		"Israel, 1:250,000, 1951": "إسرائيل: 1:250000، 1951",
		"Combined Maps, 1930s/40s": "خرائط مركّبة، عقدَي 1930/40",
		"Vector overlay, 1940s": "طَبقات مُتّجهة، عَقد 1940",
		"Vector overlay, 2020s": "طَبقات مُتّجهة، عقد 2020",
		"Information": "معلومات",
		"Description": "وَصف",
		"Survey of Palestine": "خرائط مَسح فلسطين",
		"Palestine Exploration Fund": "خرائط صندوق استكشاف فلسطين",
		"Survey of Israel": "خرائط مَسح إسرائيل",
		"British military": "خرائط الجيش البريطانيّ",
		"OpenMapTiles / OpenStreetMap Contributors": "مُساهمات من OpenMapTiles/OpenStreetMap",
		"Scale": "المِقياس",
		"Date": "التّاريخ",
		"Dates": "التّواريخ",
		"No. of map sheets": "عدد شرائح الخرائط",
		"Download": "تحميل",
		"Show places": "عرض الأماكن",
		"Show overlays": "عرض الطّبقات",
		"Buildings": "منشآت عمرانية",
		"Roads/rail": "طُرق/سِكَك",
		"Place names": "أسماء الأماكن",
		"Click anywhere on the map to see sheets available to download covering that location": "انقر/ي على أي نقطة في الخريطة لعَرض الشّرائح المُتاحة للتّحميل حول الموقِع",
		"Close downloads": "إغلاق التّحميلات",
		"Change since 1948": "التغيّير منذ 1948",
		"Population": "التعداد السّكاني",
		"Population by group": "التعداد السّكاني حسب الجماعات",
		"on other sites": "في مواقع أخرى",
		"Sheets from this base map": "شرائح من هذه الخريطة الأساسيّة",
		"Sheets from other base maps": "شرائح من خرائط أساسيّة أخرى",
		"Palestine Remembered": "مشروع فلسطين في الذّاكرة",
		"Palestine, Today": "فلسطين، اليوم",
		"Encyclopedia of the Palestine Question": "الموسوعة للقضية الفلسطينية",
		"Zochrot": "مؤسسة زوخروت",
		"Initiated and supported by Visualising Palestine": "بمُبادرة ودَعم من Visualising Palestine",
		"No data": "لا توجد بيانات",
		"Palestinian": "فلسطينيّ/ة",
		"Jewish": "يهوديّ/ة",
		"Other": "غير ذلك",
		"N/A": "لا يوجد",
		"Key dates": "تواريخ مهمة",
		"Depopulated": "مهجّرة",
		"Remaining": "باقَية",
		"Depopulated & appropriated": "مهجّرة ومُصادرة",
		"Depopulated & built over": "مهجّرة وبُني فَوقها",
		"Abandoned": "مهجورة",
		"New locality": "مَنطقة جَديدة",
		"in": "في",
		"sub-district": "قَضاء",
		"Village": "قرية",
		"City": "مدينة",
		"Illegal settlement": "مستوطنة غير شرعيّة",
		"Mixed": "مختلطة",
		"Built over": "بُني فوقها",
		"Acre": "عكا",
		"Jaffa": "يافا",
		"Beersheba": "بئر السبع",
		"Beisan": "بيسان",
		"Haifa": "حيفا",
		"Gaza": "غزة",
		"Hebron": "الخليل",
		"Jenin": "جنين",
		"Jerusalem": "القدس",
		"Nablus": "نابلس",
		"Nazareth": "الناصِرة",
		"Ramallah": "رام الله",
		"Ramle": "الرملة",
		"Safad": "صفد",
		"Tiberias": "طبريه",
		"Tulkarm": "طولكرم",
		"Welcome to Palestine Open Maps": "أهلًا بكم/ن في خَرائط فِلسطين المَفتوحة",
		"Explore, search and download historical maps and spatial data on Palestine": "استكشِف/ي وتصفّح/ي وحمّل/ي خرائط وبيانات مَكانيّة عَن فلسطين",
		"Read more": "اقرأ/ي المزيد",
		"Download hundreds of historical map sheets": "حمّل/ي المئات من الخرائط التّاريخية",
		"View data on over 2,000 places, past and present": "تصفّح/ي بيانات عن أكثر من 2000 موقع بين الماضي والحاضر",
		"Explore historical maps from the 1870s onwards": "استكشف/ي خرائط تاريخيّة منذ القَرن ١٩",
		"Overlay historical and present day maps": "ركّبي خرائط لنفس الموقع من حُقبات مختلفة",
		"View the topography of Palestine in 3D": "تجّول/ي عبر تضاريس فلسطين من خلال الرّؤية ثلاثيّة الأبعاد",
		"View past and present maps side-by-side": "قارن/ي خرائط من الماضي والحاضر جنبًا إلى جنب",
		"A high resolution basemap of satellite and aerial imagery compiled by ESRI. The imagery data comes from a variety of providers, including open data from NASA, USGS, and others. It is color-corrected and blended together into a single raster tileset.": "خريطة أساسيّة ذات دقّة عالية تحتوي على تَصوير جوي وتَصوير قمر اصطناعيّ قامت بتجميعه شَركة نُظم مَعلومات جُغرافية. تم الحُصول على البيانات الصوريّة من عدّة مصادر منها: البيانات المفتوحة لدى الإدارة الوطنية للمِلاحة الجويّة والفضاء (ناسا) وهيئة المَسح الجُيولوجي الأمريكيّة وغيرها. تم تصحيح ألوان جميع الصوّر ودَمجها ضمن مجموعة نقطيّة واحدة.",
		"A layer compiled from black and white aerial photographs captured by the British military in the 1940s. It is color-corrected and merged together into a single raster tileset.": "طَبقة مُركّبة من الصّور الجويّة بالأبيض والأسود التي التقطها الجيش البريطانيّ في الأربعينيات. تم تصحيح الألوان ودمجها معًا في مجموعة نقطيّة واحدة.",
		"This series of maps was commissioned by the Palestine Exploration Fund, a British society founded and financed by a group of Biblical archaeologists and clergymen \"for the purpose of investigating the Archaeology, Geography, manners, customs and culture, Geology and Natural History of the Holy Land.\" The maps capture much of the territory that would later fall under the British Mandate of Palestine, as well as parts of present day Lebanon, Syria and Jordan. These maps are of particular interest today, since they offer the most comprehensive record of Palestine immediately before the Zionist colonization.": "صَدرت هذه السلسلة من الخرائط بتَكليف من صُندوق استكشاف فلسطين، وهي جمعية بريطانيّة أسسها ويُموّلها مجموعة من عُلماء الآثار ورجال الدّين التوراتيين، \"لغَرض استكشاف الآثار والجغرافيا والعادات والتّقاليد والثّقافة والجيولوجيا والتّاريخ الطبيعيّ للأراضي المقدّسة\". تُغطي الخَرائط جزءًا كبيرًا من الأراضي التي وَقعت تحت الانتداب البريطانيّ على فلسطين فيما بعد، وتمتدّ إلى أجزاء من لبنان وسوريا والأردن حسب الحُدود المُعترف بها اليَوم. تَحظى هذه الخرائط بأهميّة خاصة اليوم، حيث توفّر السّجل الأشمل لفلسطين قَبل الاستعمار الصّهيوني مُباشرة.",
		"This uniquely detailed series of maps captures a large portion of mandate Palestine immediately before the Nakba. As a 'topo-cadastral' series, the sheets combine cadastral information--boundaries and names/numbers of land ownership parcels--with topographic information including contours, vegetation and human geography. There are sheets in this set dated from the early 1930s with updates up until the end of the British Mandate period, and a handful with Israeli overprints up to 1950.": "تغطّي هذه السّلسلة من الخرائط شديدة التّفصيل جزءًا كبيرًا من مساحة فلسطين الانتدابيّة ما قَبل النّكبة مُباشرة. بصفتها سلسلة \"طوبو-مساحيّة\" تجمع الشّرائح ما بين المعلومات المساحيّة (مثل الحدود والأسماء وتَرقيم قطع أراضي المُلكيّة) مع البيانات الطبوغرافية مِثل الخُطوط الكنتوريّة والغطاء النباتي والجغرافيا البشريّة. تحتوي هذه المجموعة على خرائط تعود إلى أوائل الثلاثينيّات مع تَحديثات حتى نهاية الانتداب البريطاني، بالإضافة إلى تَعديلات إسرائيليّة حتى عام 1950.",
		"This series of maps offers a unique record of the rapid transformation of the territory between the end of the 1940s and the end of the 1950s. The sheets were originally drawn by the Survey of Palestine in the final years of the British mandate period, and then overprinted with purple amendments by the nascent Survey of Israel a decade later, recording the destruction of hundreds of Palestinian communities (each labelled with the Hebrew word הרוס, meaning 'destroyed'), and the foundation of as many new Jewish settlements on their lands. The Israeli revisions also saw the addition of the 1949 Armistice lines (or 'green line') demarcating the West Bank and Gaza Strip.": "توثّق هذه السلسلة بشكل فريد التّغيير السريع الّذي طرأ على المَنطقة مَع نهاية الأربعينات وحتى نهاية الخمسينات. رُسمت الخرائط الأصلية من قِبل مشروع مَسح فلسطين في السّنوات الأخيرة من الانتداب البريطاني على فلسطين. بعد عشر سنوات، أجريَت عليها تعديلات تظهر باللّون البنفسجيّ من قبل مشروع مَسح إسرائيل الّذي حلّ محل المشروع آنف الذّكر. توثّق التّعديلات الدّمار الّذي لَحِق بالقُرى الفلسطينيّة (حيث تعلو تلك القُرى كلمة הרוס بالعبريّة والّتي تعني \"مدمّرة\"). كما توثّق إقامة أكبر عدد ممكن من المُستوطنات اليهودية على أنقاضها. كما شملت التّعديلات الإسرائيلية على خُطوط وقف إطلاق النّار (أو الخط الأخضر) كحدود للضّفة الغربية وقطاع غزّة.",
		"This set of 3 maps captures Palestine in its entirety just two years before the end of the British mandate period and the Palestinian Nakba. It is one of the few publicly available maps that captures the southern Beersheba district of the country in any detail during this period. However, though the 1945 Village Statistics record over 40,000 mostly Palestinian Bedouin residents of the district—described in the survey itself as a \"gross underestimation\" of the actual population—very few of their formal or informal settlements are marked on the map.": "تصوّر هذه المجموعة المكوّنة من 3 خرائط فلسطين كاملةً قبل عاميَن فقط من نهاية الانتداب البريطاني ووقوع النّكبة. تعدّ هذه المجموعة أحد أهم الخرائط القَليلة المُتاحة لمنطقة بئر السّبع الجنوبيّة في تلك الفترة. بينما تسجّل إحصائيات القرى عام 1945 أكثر من 40000 بدويّا فلسطينيّا مُقيما في المنطقة، يؤكد الإحصاء نفسه أن ذلك الرّقم ليس إلا \"تقديرًا أقل من الواقع بكثير\" – وبالتّالي يظهر عدد محدود جدًا من أماكن عيشهم الرّسمية أو غير الرّسمية على الخريطة.",
		"This set of 3 maps, titled 'Israel', was produced just 5 years after a near identical-looking British map in the same scale and format titled 'Palestine'. The physical geography is drawn from the same British surveys, but the major difference is the disappearance of hundreds of Palestinian communities and the appearance of a slew of new Jewish settlements in their place. The map was also among the first to be printed with the 1949 Armistice lines (or 'green line') demarcating the West Bank and Gaza Strip.": "تم إنتاج هذه المجموعة المكوّنة من 3 خرائط تحت عنوان \"إسرائيل\" بعد 5 سنوات فقط من إنتاج خريطة بريطانيّة شبه مُطابقة بنفس المقياس والشّكل تحمِل عنوان \"فلسطين\". تم الاعتماد على الاستطلاعات البريطانيّة ذاتها لرسم الجغرافيا الطبيعية، إلّا أن الاختلاف الرئيسيّ كان اختفاء مئات التّجمعات الفلسطينية وظهور عَدد كبير من المُستوطنات اليهودية الجَديدة مكانها. كما تعدّ الخريطة إحدى أولى الخرائط الّتي شملت على خطوط الهُدنة لعام 1949 (أو \"الخط الأخضر\") كحدود للضّفة الغربية وقِطاع غزة.",
		"This map layer displays different Survey of Palestine maps, depending on the zoom level. It includes all of the 1940s maps for 1:250,000, 1:100,000 and 1:20,000 scales, and includes more detailed maps from the 1930s and 1940s for the larger cities, including Jerusalem, Haifa and Jaffa (scales vary depending on the city, from 1:10,000 up to 1:1,000).": "تعرض هذه الطبقة خرائط أخرى من خرائط مسح فلسطين بعدة مقاييس، بما في ذلك جميع خرائط الأربعينيات بمقياس 1: 25.000 و 1: 100.00 و 1: 20.000. كما تحتوي على خرائط أكثر تفصيلاً من ثلاثينيات وأربعينيات القرن العشرين في المُدن الكُبرى، بما في ذلك القدس وحيفا ويافا (تختلف المقاييس حسب المدينة، من 1: 10000 حتى 1: 1000).",
		"Present day geographic features derived from OpenStreetMap, Wikidata and Natural Earth. Vector tiles generated using OpenMapTiles tools.": "تم الاعتماد على عدة مصادر في رسم الخصائص الجغرافية المعاصرة مثل: OpenStreetMap, Wikidata, Natural Earth. وتم إعداد الرّسوم المتّجهة من خلال أداة OpenMapTiles.",
		"Crowd-sourced digitisation of \"Palestine 1:20,000\" Survey of Palestine map series from the 1940s. Vector tiles generated using OpenMapTiles tools.": "تمت رقمنة خريطة \"Palestine 1:20000\" ضمن خرائط مَسح فلسطين لعقد 1940 بدعم من مصادر جماهيرية . تم إعداد الرّسوم المتّجهة من خلال أداة OpenMapTiles.",
	}
};

// export const texts = {
// 	"ar": {
// 		"العربية": "English",
// 		"ع": "en",
// 		"Palestine Open Maps": "خرائط فلسطين المفتوحة",
// 		"Palestine Open Maps community": "مجتمع خرائط فلسطين المفتوحة",
// 		"Base maps": "الخرائط",
// 		"Overlays": "الطبقات الأخرى",
// 		"Places": "البلدات",
// 		"Get updates": "تابعوا آخر التحديثات",
// 		"Download maps": "تنزيل الخرائط",
// 		"Home": "صفحة رئيسية",
// 		"About": "عن المشروع",
// 		"Get involved": "الانخراط",
// 		"Blog": "مدونة",
// 		"Contact": "اتصال",
// 		"Project vision": "رؤيتنا للمشروع",
// 		"Support us": "دعم المشروع",
// 		"Explore maps": "الخرائط",
// 		"Toggle split-screen": "تبديل تقسيم الشاشة",
// 		"Toggle 3D (experimental)": "تبديل ثلاثي الأبعاد",
// 		"Toggle places": "تبديل الأماكن",
// 		"Toggle overlays": "تبديل التراكبات",
// 		"Show layer information": "عرض معلومات الطبقة",
// 		"Find a place": "ابحث عن مكان",
// 		"Aerial imagery, 1940s": "التصوير الجوي، 1940s",
// 		"Satellite imagery, 2022": "تصوير الأقمار الصناعية، 2022",
// 		"Western Palestine, 1:63,000, 1870s": "فلسطين الغربية، 1:63,000، 1870s",
// 		"Palestine, 1:20,000, 1940s": "فلسطين، 1:20,000، 1940s",
// 		"Palestine, 1:100,000, 1940s/50s": "فلسطين، 1:100,000، 1940s/50s",
// 		"Palestine, 1:250,000, 1946": "فلسطين، 1:250,000، 1946",
// 		"Israel, 1:250,000, 1951": "إسرائيل، 1:250,000، 1951",
// 		"Combined Maps, 1930s/40s": "خرائط مدموجة، 1930s/40s",
// 		"Vector overlay, 1940s": "تراكبات فيكتور، 1940s",
// 		"Vector overlay, 2020s": "تراكبات فيكتور، 2020s",
// 		"Information": "معلومات",
// 		"Description": "وصف",
// 		"Survey of Palestine": "مسح فلسطين",
// 		"Palestine Exploration Fund": "صندوق استكشاف فلسطين",
// 		"Survey of Israel": "مسح إسرائيل",
// 		"British military": "العسكرية البريطانية",
// 		"OpenMapTiles / OpenStreetMap Contributors": "مُساهِمون OpenMapTiles / OpenStreetMap",
// 		"Scale": "المقياس",
// 		"Date": "التاريخ",
// 		"Dates": "تواريخ",
// 		"No. of map sheets": "عدد أوراق الخرائط",
// 		"Download": "تحميل",
// 		"Show places": "عرض الأماكن",
// 		"Show overlays": "عرض الطبقات المتداخلة",
// 		"Buildings": "المباني",
// 		"Roads/rail": "الطرق / السكك الحديدية",
// 		"Place names": "أسماء الأماكن",
// 		"Click anywhere on the map to see sheets available to download covering that location": "انقر في أي مكان على الخريطة لرؤية الأوراق المتاحة للتنزيل والتي تغطي تلك المنطقة",
// 		"Close downloads": "إغلاق التنزيلات",
// 		"Change since 1948": "التغيير منذ 1948",
// 		"Population": "عدد السكان",
// 		"Population by group": "عدد السكان حسب المجموعة",
// 		"on other sites": "على مواقع أخرى",
// 		"Sheets from this base map": "أوراق من هذه الخريطة",
// 		"Sheets from other base maps": "أوراق من خرائط أخرى",
// 		"Palestine Remembered": "فلسطين في الذاكرة",
// 		"Palestine, Today": "فلسطين، اليوم",
// 		"Zochrot": "ذاكرات",
// 		"Initiated and supported by": "بدأت ودعمت من خلال",
// 		"No data": "لايوجد بيانات",
// 		"Palestinian": "فلسطيني",
// 		"Jewish": "يهودي",
// 		"Other": "آخر",
// 		"N/A": "غير متاح",
// 		"Key dates": "تواريخ مهمة",
// 		"Depopulated": "دمرت",
// 		"Remaining": "لا تزال قائمة",
// 		"Depopulated & appropriated": "دمرت واستولى",
// 		"Depopulated & built over": "دمرت وبنيت فوق",
// 		"Abandoned": "مهجور",
// 		"New locality": "مكان جديد",
// 		"in": "في",
// 		"sub-district": "قضاء",
// 		"Village": "قرية",
// 		"City": "مدينة",
// 		"Illegal settlement": "مستوطنة غير قانونية",
// 		"Mixed": "مختلطة",
// 		"Built over": "بنيت فوق",
// 		"Acre": "عكا",
// 		"Jaffa": "يافا",
// 		"Beersheba": "بئر السبع",
// 		"Beisan": "بيسان",
// 		"Haifa": "حيفا",
// 		"Gaza": "غزة",
// 		"Hebron": "الخليل",
// 		"Jenin": "جنين",
// 		"Jerusalem": "القدس",
// 		"Nablus": "نابلس",
// 		"Nazareth": "الناصِرة",
// 		"Ramallah": "رام الله",
// 		"Ramle": "الرملة",
// 		"Safad": "صفد",
// 		"Tiberias": "طبريه",
// 		"Tulkarm": "طولكرم",
// 		"Welcome to<br>Palestine Open Maps": "مرحبًا بك في<br>خرائط فلسطين المفتوحة",
// 		"Explore, search and download historical maps and spatial data on Palestine": "استكشف وابحث وقم بتنزيل الخرائط التاريخية والبيانات المكانية عن فلسطين",
// 		"Read more": "اقرأ المزيد",
// 		"Download hundreds of historical map sheets": "حمّل مئات أوراق الخرائط التاريخية",
// 		"View data on over 2,000 places, past and present": "شاهد البيانات عن أكثر من 2000 مكان، في الماضي والحاضر",
// 		"Explore historical maps from the 1870s onwards": "استكشف الخرائط التاريخية من السبعينيات من القرن التاسع عشر فصاعدًا",
// 		"Overlay historical and present day maps": "ضع خرائط الماضي والحاضر فوق بعضها البعض",
// 		"View the topography of Palestine in 3D": "شاهد تضاريس فلسطين بتقنية ثلاثية الأبعاد",
// 		"View past and present maps side-by-side": "شاهد خرائط الماضي والحاضر جنبًا إلى جنب",
// 		"A high resolution basemap of satellite and aerial imagery compiled by ESRI. The imagery data comes from a variety of providers, including open data from NASA, USGS, and others. It is color-corrected and blended together into a single raster tileset.": "خريطة أساس عالية الدقة من صور الأقمار الصناعية والتصوير الجوي تم إعدادها من قبل ESRI. تم الحصول على البيانات من مجموعة متنوعة من المزودين، بما في ذلك البيانات المفتوحة من وكالة ناسا والمسح الجيولوجي الأمريكي وغيرها. تم تصحيح الألوان ودمجها معًا في مجموعة بيانات الصورة النقطية الواحدة.",
// 		"A layer compiled from black and white aerial photographs captured by the British military in the 1940s. It is color-corrected and merged together into a single raster tileset.": "طبقة تم إعدادها من صور جوية بالأبيض والأسود التقطتها العسكرية البريطانية في الأربعينات. تم تصحيح الألوان ودمجها معًا في مجموعة بيانات الصورة النقطية الواحدة.",
// 		"This series of maps was commissioned by the Palestine Exploration Fund, a British society founded and financed by a group of Biblical archaeologists and clergymen \"for the purpose of investigating the Archaeology, Geography, manners, customs and culture, Geology and Natural History of the Holy Land.\" The maps capture much of the territory that would later fall under the British Mandate of Palestine, as well as parts of present day Lebanon, Syria and Jordan. These maps are of particular interest today, since they offer the most comprehensive record of Palestine immediately before the Zionist colonization.": "هذه السلسلة من الخرائط تم تكليفها من قبل صندوق استكشاف فلسطين، وهي جمعية بريطانية تأسست وتموّلت من قبل مجموعة من علماء الآثار الكتابيين ورجال الدين \"لأغراض تحقيق الآثار الأثرية والجغرافية والعادات والتقاليد والثقافة والجيولوجيا والتاريخ الطبيعي في الأراضي المقدسة.\" تغطي الخرائط الكثير من الأراضي التي ستقع لاحقًا تحت الانتداب البريطاني في فلسطين، بالإضافة إلى بعض مناطق لبنان وسوريا والأردن الحالية. تعتبر هذه الخرائط مثيرة للاهتمام اليوم، حيث توفر أكثر سجل شامل لفلسطين مباشرةً قبل الاستيطان الصهيوني.",
// 		"This uniquely detailed series of maps captures a large portion of mandate Palestine immediately before the Nakba. As a 'topo-cadastral' series, the sheets combine cadastral information--boundaries and names/numbers of land ownership parcels--with topographic information including contours, vegetation and human geography. There are sheets in this set dated from the early 1930s with updates up until the end of the British Mandate period, and a handful with Israeli overprints up to 1950.": "هذه السلسلة المفصلة والفريدة من نوعها من الخرائط تلتقط جزءًا كبيرًا من فلسطين الانتدابية مباشرة قبل النكبة. كسلسلة \"التوبو-كاداسترال\"، تجمع الورقات بين المعلومات الكاداسترالية - الحدود وأسماء/أرقام حقول الملكية الأرضية - مع المعلومات التضاريسية بما في ذلك المنحنيات المستوية والنباتات والجغرافيا البشرية. تتضمن السلسلة ورقات تعود إلى أوائل الثلاثينيات مع التحديثات حتى نهاية فترة الانتداب البريطاني، بالإضافة إلى عدد قليل من الورقات التي تم وضع علامات إسرائيلية عليها حتى عام 1950. هذا المستوى من التفاصيل والدقة يجعل الخرائط موردًا قيمًا للباحثين الذين يدرسون تاريخ وجغرافيا فلسطين.",
// 		"This series of maps offers a unique record of the rapid transformation of the territory between the end of the 1940s and the end of the 1950s. The sheets were originally drawn by the Survey of Palestine in the final years of the British mandate period, and then overprinted with purple amendments by the nascent Survey of Israel a decade later, recording the destruction of hundreds of Palestinian communities (each labelled with the Hebrew word הרוס, meaning 'destroyed'), and the foundation of as many new Jewish settlements on their lands. The Israeli revisions also saw the addition of the 1949 Armistice lines (or 'green line') demarcating the West Bank and Gaza Strip.": "هذه السلسلة من الخرائط تقدم سجلاً فريداً للتحول السريع للأراضي بين نهاية الأربعينيات ونهاية الخمسينيات. تم رسم الأوراق في الأصل من قبل المسح الفلسطيني في السنوات الأخيرة من فترة الانتداب البريطاني، ومن ثم تم طباعة تعديلات باللون الأرجواني من قبل مسح إسرائيل الناشئ بعد عقد من الزمن، مسجلةً تدمير مئات المجتمعات الفلسطينية (والمسماة بالكلمة العبرية \"הרוס\"، والتي تعني \"مدمرة\")، وتأسيس العديد من المستوطنات اليهودية الجديدة على أراضيهم. شهدت التعديلات الإسرائيلية أيضًا إضافة خطوط التهدئة العامة لعام 1949 (أو \"الخط الأخضر\") الفاصل بين الضفة الغربية وقطاع غزة.",
// 		"This set of 3 maps captures Palestine in its entirety just two years before the end of the British mandate period and the Palestinian Nakba. It is one of the few publicly available maps that captures the southern Beersheba district of the country in any detail during this period. However, though the 1945 Village Statistics record over 40,000 mostly Palestinian Bedouin residents of the district—described in the survey itself as a \"gross underestimation\" of the actual population—very few of their formal or informal settlements are marked on the map.": "هذه المجموعة من 3 خرائط تسجل فلسطين بأكملها قبل عامين فقط من نهاية الانتداب البريطاني ونكبة الشعب الفلسطيني. إنها واحدة من الخرائط المتاحة للجمهور التي تسجل منطقة بئر السبع الجنوبية للبلاد بأي تفصيل خلال هذه الفترة. ومع ذلك، على الرغم من أن إحصاءات القرى لعام 1945 تسجل وجود أكثر من 40،000 من سكان البدو الفلسطيني في المنطقة - والتي وصفت في المسح نفسه باعتبارها \"تقديراً غير دقيق للغاية\" للسكان الفعليين - إلا أنه لا يوجد القليل من المستوطنات الرسمية أو غير الرسمية التي يتم وضع علامات عليها على الخريطة.",
// 		"This set of 3 maps, titled 'Israel', was produced just 5 years after a near identical-looking British map in the same scale and format titled 'Palestine'. The physical geography is drawn from the same British surveys, but the major difference is the disappearance of hundreds of Palestinian communities and the appearance of a slew of new Jewish settlements in their place. The map was also among the first to be printed with the 1949 Armistice lines (or 'green line') demarcating the West Bank and Gaza Strip.": "هذه مجموعة من ثلاث خرائط، بعنوان \"إسرائيل\"، تم إنتاجها قبل 5 سنوات فقط من خريطة بريطانية مماثلة بنفس المقياس والتنسيق بعنوان \"فلسطين\". الجغرافيا الطبيعية مستمدة من نفس المسوحات البريطانية، لكن الفرق الرئيسي هو اختفاء مئات المجتمعات الفلسطينية وظهور العديد من المستوطنات اليهودية في مكانها. وكانت الخريطة أيضاً من بين أول الخرائط التي تم طباعتها بخطوط التهدئة لعام 1949 (أو \"الخط الأخضر\") التي تفصل الضفة الغربية وقطاع غزة.",
// 		"This map layer displays different Survey of Palestine maps, depending on the zoom level. It includes all of the 1940s maps for 1:250,000, 1:100,000 and 1:20,000 scales, and includes more detailed maps from the 1930s and 1940s for the larger cities, including Jerusalem, Haifa and Jaffa (scales vary depending on the city, from 1:10,000 up to 1:1,000).": "هذه الطبقة الخرائطية تعرض خرائط مسح فلسطين المختلفة، حسب مستوى التكبير. تشمل كل الخرائط للمقاييس 1:250,000 و 1:100,000 و 1:20,000 في الأربعينات، وتتضمن خرائط مفصلة أكثر للمدن الكبرى من الثلاثينات والأربعينات، بما في ذلك القدس وحيفا ويافا (تتفاوت المقاييس حسب المدينة، من 1:10,000 إلى 1:1,000).",
// 		"Present day geographic features derived from OpenStreetMap, Wikidata and Natural Earth. Vector tiles generated using OpenMapTiles tools.": "المعالم الجغرافية الحالية المشتقة من OpenStreetMap وWikidata وNatural Earth. البلاطات الناقلة للبيانات المتجهة تم إنتاجها باستخدام أدوات OpenMapTiles.",
// 		"Crowd-sourced digitisation of \"Palestine 1:20,000\" Survey of Palestine map series from the 1940s. Vector tiles generated using OpenMapTiles tools.": "رقمنة المصادر المدمجة بالمجتمع لسلسلة خرائط \"فلسطين 1:20,000\" لمسح فلسطين من الأراضي الفلسطينية في الأربعينيات. تم إنشاء بلاطات البيانات النقطية باستخدام أدوات OpenMapTiles."
// 	}
// };